name: Dialyzer

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: ci
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 20.3.8.26
              elixir: 1.8.2
          - pair:
              otp: 23.2.5
              elixir: 1.11.3
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: |
          epmd -daemon
          mix deps.unlock --all
          mix deps.get
          mix quality.ci
